name: Build and Upload WordPress Plugin ZIP

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "PLUGIN_SLUG=simple-cookie-consent" >> $GITHUB_ENV
          echo "ZIP_NAME=simple-cookie-consent.zip" >> $GITHUB_ENV

      - name: Build plugin folder
        run: |
          mkdir -p build/${PLUGIN_SLUG}

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.gitattributes' \
            --exclude='.gitignore' \
            --exclude='node_modules' \
            --exclude='tests' \
            --exclude='*.zip' \
            ./ build/${PLUGIN_SLUG}/

      - name: Create ZIP
        run: |
          cd build/${PLUGIN_SLUG}
          zip -r "../../${ZIP_NAME}" .
          cd ../..

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: simple-cookie-consent.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
